---
datatype: "sg"
noisetype: "gaussian_smear"
sigma: 0.4
priors:
  f_0:
    distribution: "uniform"
    low: 0.1
    high: 1.0
  tau:
    distribution: "uniform"
    low: 1.0
    high: 4.0
  shift:
    distribution: "uniform"
    low: -2.0
    high: 2.0
num_samples: 100000
num_repeats: 10
t_start: -10
t_end: 10
t_num_points: 500
method: "torch"
seed: 42